pieShop/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using pieShop.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace pieShop.Controllers
{
    [Authorize]
    public class FeedbackController : Controller
    {
        private readonly IFeedbackRepository _feedbackRepository;

        public FeedbackController(IFeedbackRepository feedbackRepository)
        {
            _feedbackRepository = feedbackRepository;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        //POST: /<controller>/


        [HttpPost]
        public IActionResult Index(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _feedbackRepository.AddFeedback(feedback);
                return RedirectToAction("FeedbackComplete");
            }

            return View(feedback);
        }

        public IActionResult FeedbackComplete()
        {
            return View();
        }
    }
}

pieShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SignInManager
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href ="/lib/bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/content/style.css"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<div class="row">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index" class="navbar-brand">Pie Shop</a></li>
                    <li><a asp-controller="Feedback" asp-action="Index">Feedback</a></li>
                </ul>
                @if (SignInManager.IsSignedIn(User))
                {
                    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
                          method="post" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a id="registerLink" asp-controller="Account" asp-action="Register">Register</a></li>
                        <li><a id="loginLink" asp-controller="Account" asp-action="Login">Log in</a></li>
                    </ul>
                }      
            </div>
        </div>
   
  
                
    </nav>
</div>


<div class="container body-content">
    <div class="row">
        @RenderBody()
    </div>
</div>
</body>
</html>